#!/system/bin/sh
#ModeSelektor v2.2
#Author Davide Di Battista
#2017-2018
#License GNU v3
#Device Xiaomi Redmi Note 3
#Ultra Battery

ModeSelektor( ) {

echo "--------------------------------------------------------------"
echo "|||ULTRA BATTERY START|||"
echo "--------------------------------------------------------------"
echo "--------------------------------------------------------------"
echo "SET CPU GOVERNOR"
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 666 /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "interactive" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo "Cpu governor setted"
echo ".............................................................."
echo "SET MIN CPU FREQ"
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "400000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
chmod 666 /sys/module/msm_performance/parameters/cpu_min_freq
echo "0:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "1:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "2:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "3:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
chmod 666 /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq
echo "400000" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq
chmod 666 /sys/module/msm_performance/parameters/cpu_min_freq
echo "4:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "5:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "Min cpu freq setted"
echo ".............................................................."
echo "SET MAX CPU FREQ"
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "1440000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
chmod 666 /sys/module/msm_performance/parameters/cpu_max_freq
echo "0:1440000" > /sys/module/msm_performance/parameters/cpu_max_freq
echo "1:1440000" > /sys/module/msm_performance/parameters/cpu_max_freq
echo "2:1440000" > /sys/module/msm_performance/parameters/cpu_max_freq
echo "3:1440000" > /sys/module/msm_performance/parameters/cpu_max_freq
chmod 666 /sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq
echo "1804800" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq
chmod 666 /sys/module/msm_performance/parameters/cpu_max_freq
echo "4:400000" > /sys/module/msm_performance/parameters/cpu_max_freq
echo "5:400000" > /sys/module/msm_performance/parameters/cpu_max_freq
echo "Max cpu freq setted"
echo ".............................................................."
echo "SET CPU GOVERNOR PARAMETERS"
echo "80" >/sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load
echo "1017600" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/io_is_busy
echo "40000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time
echo "80 1305600:90" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/use_sched_load
echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/use_migration_notif
echo "59000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
echo "50000" >/sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_rate
echo "19000 1382600:39000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/above_hispeed_delay
echo "85" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/go_hispeed_load
echo "1190400" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq
echo "0" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/io_is_busy
echo "40000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/min_sample_time
echo 85 1382600:90 1747200:80 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads
echo "1" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/use_sched_load
echo "1" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/use_migration_notif
echo "60000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/max_freq_hysteresis
echo "50000" >/sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_rate
echo "Cpu governor parameters setted"
echo ".............................................................."
echo "SET INPUT BOOST"
if [ -d /sys/module/cpu_boost/parameters ]; then
    echo 0:0 1:0 2:0 3:0 4:0 5:0 > /sys/module/cpu_boost/parameters/input_boost_freq
    echo "Input boost setted"
else
    echo "Is not possible set the input boost"
fi
echo ".............................................................."
echo "SET TOUCH BOOST"
if [ -d /sys/module/msm_performance/parameters ]; then
    echo 0 > /sys/module/msm_performance/parameters/touchboost
    echo "touch boost setted"
else
    echo "Is not possible set the touch boost"
fi
echo ".............................................................."
echo "SET SCHED BOOST"
echo "0" > /proc/sys/kernel/sched_boost
echo "Sched boost setted"
echo ".............................................................."
echo "SET LPM"
chmod 666 /sys/module/lpm_levels/parameters/sleep_disabled
echo "N" > /sys/module/lpm_levels/parameters/sleep_disabled chmod 664 /sys/module/lpm_levels/parameters/sleep_disabled
echo "Lpm setted"
echo ".............................................................."
echo "SET CPUBW GOVERNOR"
if [ -d /sys/class/devfreq/cpubw ]; then
  echo "powersave" > /sys/class/devfreq/cpubw/governor
  else
  echo "powersave" > /sys/class/devfreq/qcom,cpubw.49/governor
fi
echo "Cpubw governor setted"
echo ".............................................................."
echo "SET STOCK HOTPLUG"
if [ -f /sys/devices/system/cpu/cpu4/core_ctl/global_state ]; then
    echo "2" > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus
    echo "4" > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus
    echo "0" > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus
    echo "0" > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus
    echo "Hotplug setted"
else
    echo "Is not possible set hotplug"
fi
echo ".............................................................."
echo "SET GPU GOVERNOR"
echo "powersave" > /sys/class/kgsl/kgsl-3d0/devfreq/governor
echo "Gpu governor setted"
echo ".............................................................."
echo "SET ADRENO IDLER"
if [ -d /sys/module/adreno_idler/parameters ]; then
    echo "Y" > /sys/module/adreno_idler/parameters/adreno_idler_active
    echo "Adreno idler setted"
else
    echo "Is not possible set adreno idler"
fi
echo ".............................................................."
echo "SET ARCH POWER"
if [ -f /sys/kernel/sched/arch_power ]; then
    echo "1" > /sys/kernel/sched/arch_power
    echo "Arch power setted"
else
    echo "Is not possible set arch power"
fi
echo ".............................................................."
echo "SET SCHEDULER"
SchedList=$( cat /sys/block/mmcblk0/queue/scheduler )
zen="zen"
if [ "${SchedList/$zen}" = "$SchedList" ] ; then
    echo "Is not possible set the scheduler"
else
    echo "zen" > /sys/block/mmcblk0/queue/scheduler
    echo "2048" > /sys/block/mmcblk0/queue/read_ahead_kb
    echo "Scheduler setted"
fi
echo ".............................................................."
echo "SET ZRAM"
swapoff /dev/block/zram0 > /dev/null 2>&1
echo "1" > /sys/block/zram0/reset
echo "524288000" > /sys/block/zram0/disksize
mkswap /dev/block/zram0 > /dev/null 2>&1
swapon /dev/block/zram0 > /dev/null 2>&1
echo "100" > /proc/sys/vm/swappiness
echo "Zram setted"
echo ".............................................................."
echo "SET ENTROPY"
echo "64" > /proc/sys/kernel/random/read_wakeup_threshold
echo "128" > /proc/sys/kernel/random/write_wakeup_threshold
echo "Entropy setted"
echo "--------------------------------------------------------------"
echo "--------------------------------------------------------------"
echo "||| ULTRA BATTERY END |||"
echo "--------------------------------------------------------------"
'date'
echo "--------------------------------------------------------------"
}
ModeSelektor 2>&1 | tee ~/sdcard/ModeSelektor/LastLog.log
