#!/system/bin/sh
#ModeSelektor v2.4
#Author Davide Di Battista
#2017-2018
#License GNU v3
#Device Xiaomi Redmi Note 3
#Battery

if [ -f /sys/devices/system/cpu/cpu4/core_ctl/global_state ]; then
    echo "4" > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus;
    echo "4" > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;
    echo "2" > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
    echo "2" > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;
fi
sleep 1
ModeSelektor( ) {
echo "--------------------------------------------------------"
echo "|  BATTERY start  |"
echo "--------------------------------------------------------"
echo "SET CPU GOVERNOR"
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 666 /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "interactive" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo "Cpu governor setted"
echo ".............................................................."
echo "SET MIN CPU FREQ"
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "400000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
chmod 666 /sys/module/msm_performance/parameters/cpu_min_freq
echo "0:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "1:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "2:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "3:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
chmod 666 /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq
echo "400000" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq
chmod 666 /sys/module/msm_performance/parameters/cpu_min_freq
echo "4:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "5:400000" > /sys/module/msm_performance/parameters/cpu_min_freq
echo "Min cpu freq setted"
echo ".............................................................."
echo "SET CPU GOVERNOR PARAMETERS"
echo "85" >/sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load
echo "691200" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/io_is_busy
echo "40000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time
echo "85 1305600:95" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/use_sched_load
echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/use_migration_notif
echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
echo "20000" >/sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_rate
echo "19000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/above_hispeed_delay
echo "90" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/go_hispeed_load
echo "1190400" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq
echo "0" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/io_is_busy
echo "40000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/min_sample_time
echo 90 1190400:85 1382400:95 1747200:85 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads
echo "1" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/use_sched_load
echo "1" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/use_migration_notif
echo "60000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/max_freq_hysteresis
echo "20000" >/sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_rate
echo "Cpu governor parameters setted"
echo ".............................................................."
echo "SET INPUT BOOST"
if [ -d /sys/module/cpu_boost/parameters ]; then
    echo 0:691200 1:691200 2:691200 3:691200 4:0 5:0 > /sys/module/cpu_boost/parameters/input_boost_freq
    echo 40 > /sys/module/cpu_boost/parameters/input_boost_ms
    echo 1 > /sys/module/cpu_boost/parameters/input_boost_enabled
    echo "Input boost setted"
else
    echo "Is not possible set the input boost"
fi
echo ".............................................................."
echo "SET TOUCH BOOST"
if [ -f /sys/module/msm_performance/parameters/touchboost ]; then
    echo 0 > /sys/module/msm_performance/parameters/touchboost
    echo "touch boost setted"
else
    echo "Is not possible set the touch boost"
fi
echo ".............................................................."
echo "SET SCHED BOOST"
echo "0" > /proc/sys/kernel/sched_boost
echo "Sched boost setted"
echo ".............................................................."
echo "SET LPM"
chmod 666 /sys/module/lpm_levels/parameters/sleep_disabled
echo "N" > /sys/module/lpm_levels/parameters/sleep_disabled chmod 664 /sys/module/lpm_levels/parameters/sleep_disabled
echo "Lpm setted"
echo ".............................................................."
echo "SET CPUBW GOVERNOR"
if [ -d /sys/class/devfreq/cpubw ]; then
  echo "bw_hwmon" > /sys/class/devfreq/cpubw/governor
  else
  echo "bw_hwmon" > /sys/class/devfreq/qcom,cpubw.49/governor
fi
echo "Cpubw governor setted"
echo ".............................................................."
echo "SET STOCK HOTPLUG"
if [ -f /sys/devices/system/cpu/cpu4/core_ctl/global_state ]; then
    echo "2" > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus
    echo "4" > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus
    echo "20 20 20 20" > /sys/devices/system/cpu/cpu0/core_ctl/busy_down_thres
    echo "60 60 60 60" > /sys/devices/system/cpu/cpu0/core_ctl/busy_up_thres
    echo "200" > /sys/devices/system/cpu/cpu0/core_ctl/offline_delay_ms
    echo "1" > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus
    echo "2" > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus
    echo "100" > /sys/devices/system/cpu/cpu4/core_ctl/offline_delay_ms
    echo "40 40" > /sys/devices/system/cpu/cpu4/core_ctl/busy_down_thres
    echo "68 68" > /sys/devices/system/cpu/cpu4/core_ctl/busy_up_thres
    echo "Hotplug setted"
else
    echo "Is not possible set hotplug"
fi
echo ".............................................................."
echo "SET GPU GOVERNOR"
echo "msm-adreno-tz" > /sys/class/kgsl/kgsl-3d0/devfreq/governor
echo "Gpu governor setted"
echo ".............................................................."
echo "SET GPU MAX FREQ"
echo "480000000" > /sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk
echo "Gpu max freq setted"
echo ".............................................................."
echo "SET ENTROPY"
echo "64" > /proc/sys/kernel/random/read_wakeup_threshold
echo "128" > /proc/sys/kernel/random/write_wakeup_threshold
echo "Entropy setted"
echo "--------------------------------------------------------"
echo "|  BATTERY end  |"
'date'
echo "--------------------------------------------------------"
}
ModeSelektor 2>&1 | tee ~/sdcard/ModeSelektor/LastLog.log;
exit