#!/system/bin/sh
#ModeSelektor v2.5.3
#Author Davide Di Battista
#Contributor Stefano 99
#2017-2018
#License GNU v3
#Device Xiaomi Redmi Note 3
#Thanks to Ryuinferno, lambgx02
#Seeder Off

pkill rngd
echo 200 > /proc/sys/vm/dirty_expire_centisecs
DefaultMode=$(cat /sdcard/ModeSelektor/Config/DefaultMode.txt)
B="Battery"
if [ $DefaultMode == $B ]; then
    echo "128" > /proc/sys/kernel/random/read_wakeup_threshold
    echo "64" > /proc/sys/kernel/random/write_wakeup_threshold
else
    echo "512" > /proc/sys/kernel/random/read_wakeup_threshold
    echo "256" > /proc/sys/kernel/random/write_wakeup_threshold
fi