#!/system/bin/sh
#ModeSelektor v2.5.1
#Author Davide Di Battista
#Contributor Stefano 99
#2017-2018
#License GNU v3
#Device Xiaomi Redmi Note 3
#Thanks to Ryuinferno, lambgx02
#Seeder Install

mount -o rw,remount /system
cp /sdcard/ModeSelektor/rngd /system/xbin/rngd;
chmod 755 /system/xbin/rngd;
chown 0.2000 /system/xbin/rngd;
mount -o ro,remount /system